import os
import json
import concurrent.futures
from openai import OpenAI

# Global singleton for vLLM offline engine to prevent reloading multiple times in memory
_VLLM_ENGINE_SINGLETON = None

def extract_json(text: str) -> dict:
    """
    Robust JSON extraction utility.
    Strips potential <think>...</think> tags and markdown code blocks before parsing.
    """
    text_clean = text.strip()
    
    # Strip <think>...</think> tags if generated by reasoning models (e.g. DeepSeek-R1)
    if "<think>" in text_clean:
        parts = text_clean.split("</think>")
        if len(parts) > 1:
            text_clean = parts[-1].strip()
            
    # Remove markdown code block fences
    if text_clean.startswith("```json"):
        text_clean = text_clean[7:]
    elif text_clean.startswith("```"):
        text_clean = text_clean[3:]
        
    if text_clean.endswith("```"):
        text_clean = text_clean[:-3]
        
    text_clean = text_clean.strip()
    
    # Attempt parsing directly
    try:
        return json.loads(text_clean)
    except json.JSONDecodeError:
        # Fallback: search for first '{' and last '}'
        start = text_clean.find('{')
        end = text_clean.rfind('}')
        if start != -1 and end != -1:
            try:
                return json.loads(text_clean[start:end+1])
            except json.JSONDecodeError:
                pass
        raise ValueError(f"Could not extract valid JSON from LLM output: {text}")


class LLMClient:
    """
    Unified LLM Client supporting both API (OpenAI client) and vLLM (Offline Inference) modes.
    """

    def __init__(self, config: dict):
        self.config = config
        llm_settings = config.get("llm_settings", {})
        self.mode = llm_settings.get("mode", "api").lower()
        
        # Generation parameters
        self.gen_params = config.get("generation_params", {})
        
        if self.mode == "api":
            api_cfg = llm_settings.get("api", {})
            provider = "openai"
            
            # Retrieve API Key from config or env variable
            api_key = api_cfg.get("api_key") or os.getenv("OPENAI_API_KEY")
            base_url = api_cfg.get("base_url", "https://api.openai.com/v1")
            self.model = api_cfg.get("model", "gpt-4o-mini")
            
            self.client = OpenAI(api_key=api_key, base_url=base_url)
        elif self.mode == "vllm":
            # Model details are read when initializing the engine
            vllm_cfg = llm_settings.get("vllm", {})
            self.model = vllm_cfg.get("model_path", "")
        else:
            raise ValueError(f"Unsupported LLM mode: {self.mode}")

    def _get_vllm_engine(self):
        """
        Instantiate or retrieve the shared vLLM engine singleton.
        Enforces that the model path MUST exist locally as a directory to prevent automatic downloading.
        """
        global _VLLM_ENGINE_SINGLETON
        if _VLLM_ENGINE_SINGLETON is None:
            vllm_cfg = self.config.get("llm_settings", {}).get("vllm", {})
            model_path = vllm_cfg.get("model_path", "")
            
            # Resolve relative model paths if any
            resolved_path = os.path.abspath(model_path)
            if not os.path.isdir(resolved_path):
                # Try resolving relative to project root (parent directory of the agents module)
                script_dir = os.path.dirname(os.path.abspath(__file__))
                project_root = os.path.dirname(script_dir)
                potential_root_path = os.path.abspath(os.path.join(project_root, model_path))
                if os.path.isdir(potential_root_path):
                    resolved_path = potential_root_path

            # Enforce that the model path MUST exist locally as a directory
            if not os.path.isdir(resolved_path):
                raise FileNotFoundError(
                    f"vLLM Local model path '{resolved_path}' does not exist or is not a directory. "
                    f"Automatic downloading is disabled. Only pre-downloaded weights are allowed."
                )

            print(f"Initializing vLLM Offline Engine (Singleton) with local model at: {resolved_path}")
            from vllm import LLM
            _VLLM_ENGINE_SINGLETON = LLM(
                model=resolved_path,
                gpu_memory_utilization=vllm_cfg.get("gpu_memory_utilization", 0.92),
                tensor_parallel_size=vllm_cfg.get("tensor_parallel_size", 1),
                max_model_len=vllm_cfg.get("max_model_len", 40960),
                enable_chunked_prefill=vllm_cfg.get("enable_chunked_prefill", True),
            )
        return _VLLM_ENGINE_SINGLETON

    def _generate_single_api(self, prompt: str) -> str:
        """
        Send a single generation request to the API.
        """
        # Determine extra fields if supported
        extra_body = {}
        # OpenAI doesn't natively support top_k or repetition_penalty, but compatible endpoints might
        # frequency_penalty can be mapped or passed in extra_body if needed.
        
        response = self.client.chat.completions.create(
            model=self.model,
            messages=[
                {"role": "system", "content": "You are a helpful assistant."},
                {"role": "user", "content": prompt}
            ],
            temperature=self.gen_params.get("temperature", 0.6),
            max_tokens=self.gen_params.get("max_new_tokens", 10240),
            top_p=self.gen_params.get("top_p", 0.95),
            response_format={"type": "json_object"}
        )
        return response.choices[0].message.content

    def generate_batch(self, prompts: list) -> list:
        """
        Generate completions for a list of prompts.
        In API mode, requests run concurrently using a ThreadPoolExecutor.
        In vLLM mode, prompts are fed into the vLLM engine for batched GPU inference.
        """
        if not prompts:
            return []

        if self.mode == "api":
            from tqdm import tqdm
            results = [None] * len(prompts)
            max_workers = min(len(prompts), 16)
            with concurrent.futures.ThreadPoolExecutor(max_workers=max_workers) as executor:
                futures = {
                    executor.submit(self._generate_single_api, prompt): idx 
                    for idx, prompt in enumerate(prompts)
                }
                for future in tqdm(concurrent.futures.as_completed(futures), total=len(prompts), desc="Calling LLM API"):
                    idx = futures[future]
                    try:
                        results[idx] = future.result()
                    except Exception as e:
                        print(f"Error during API completion for prompt index {idx}: {e}")
                        results[idx] = ""
            return results
            
        elif self.mode == "vllm":
            from vllm import SamplingParams
            llm = self._get_vllm_engine()
            
            # Setup SamplingParams using configuration settings
            sp = SamplingParams(
                temperature=self.gen_params.get("temperature", 0.6),
                top_p=self.gen_params.get("top_p", 0.95),
                top_k=self.gen_params.get("top_k", 20),
                repetition_penalty=self.gen_params.get("repetition_penalty", 1.3),
                max_tokens=self.gen_params.get("max_new_tokens", 10240),
            )
            
            # Run vLLM batch generation with progress bar enabled
            outputs = llm.generate(prompts, sp, use_tqdm=True)
            return [out.outputs[0].text for out in outputs]
            
        return []
